#!/bin/bash
g++ -std=c++11 -march=core2 -fexpensive-optimizations -O3 -Wall -std=c++11 -I../Library/include -I../../external/include -I/home/liliane/Documentos/Libs/glfw-3.2/build/src -I/usr/include/freetype2 -Iinclude -c /home/liliane/Documentos/GIT/gcgtube/source/Library/Text2D.cpp -o obj/Release/Library/Text2D.o
g++ -std=c++11 -march=core2 -fexpensive-optimizations -O3 -Wall -std=c++11 -I../Library/include -I../../external/include -I/home/liliane/Documentos/Libs/glfw-3.2/build/src -I/usr/include/freetype2 -Iinclude -c /home/liliane/Documentos/GIT/gcgtube/source/Visualizer/Block.cpp -o obj/Release/Visualizer/Block.o
g++ -std=c++11 -march=core2 -fexpensive-optimizations -O3 -Wall -std=c++11 -I../Library/include -I../../external/include -I/home/liliane/Documentos/Libs/glfw-3.2/build/src -I/usr/include/freetype2 -Iinclude -c /home/liliane/Documentos/GIT/gcgtube/source/Visualizer/CatmullRom.cpp -o obj/Release/Visualizer/CatmullRom.o
g++ -std=c++11 -march=core2 -fexpensive-optimizations -O3 -Wall -std=c++11 -I../Library/include -I../../external/include -I/home/liliane/Documentos/Libs/glfw-3.2/build/src -I/usr/include/freetype2 -Iinclude -c /home/liliane/Documentos/GIT/gcgtube/source/Visualizer/Contact.cpp -o obj/Release/Visualizer/Contact.o
g++ -std=c++11 -march=core2 -fexpensive-optimizations -O3 -Wall -std=c++11 -I../Library/include -I../../external/include -I/home/liliane/Documentos/Libs/glfw-3.2/build/src -I/usr/include/freetype2 -Iinclude -c /home/liliane/Documentos/GIT/gcgtube/source/Visualizer/DrawableNanotube.cpp -o obj/Release/Visualizer/DrawableNanotube.o
g++ -std=c++11 -march=core2 -fexpensive-optimizations -O3 -Wall -std=c++11 -I../Library/include -I../../external/include -I/home/liliane/Documentos/Libs/glfw-3.2/build/src -I/usr/include/freetype2 -Iinclude -c /home/liliane/Documentos/GIT/gcgtube/source/Visualizer/DrawableSpheres.cpp -o obj/Release/Visualizer/DrawableSpheres.o
g++ -std=c++11 -march=core2 -fexpensive-optimizations -O3 -Wall -std=c++11 -I../Library/include -I../../external/include -I/home/liliane/Documentos/Libs/glfw-3.2/build/src -I/usr/include/freetype2 -Iinclude -c /home/liliane/Documentos/GIT/gcgtube/source/Visualizer/Forest.cpp -o obj/Release/Visualizer/Forest.o
g++ -std=c++11 -march=core2 -fexpensive-optimizations -O3 -Wall -std=c++11 -I../Library/include -I../../external/include -I/home/liliane/Documentos/Libs/glfw-3.2/build/src -I/usr/include/freetype2 -Iinclude -c /home/liliane/Documentos/GIT/gcgtube/source/Visualizer/Graph.cpp -o obj/Release/Visualizer/Graph.o
g++ -std=c++11 -march=core2 -fexpensive-optimizations -O3 -Wall -std=c++11 -I../Library/include -I../../external/include -I/home/liliane/Documentos/Libs/glfw-3.2/build/src -I/usr/include/freetype2 -Iinclude -c /home/liliane/Documentos/GIT/gcgtube/source/Visualizer/Laplacian.cpp -o obj/Release/Visualizer/Laplacian.o
g++ -std=c++11 -march=core2 -fexpensive-optimizations -O3 -Wall -std=c++11 -I../Library/include -I../../external/include -I/home/liliane/Documentos/Libs/glfw-3.2/build/src -I/usr/include/freetype2 -Iinclude -c /home/liliane/Documentos/GIT/gcgtube/source/Visualizer/LinearSolver.cpp -o obj/Release/Visualizer/LinearSolver.o
g++ -std=c++11 -march=core2 -fexpensive-optimizations -O3 -Wall -std=c++11 -I../Library/include -I../../external/include -I/home/liliane/Documentos/Libs/glfw-3.2/build/src -I/usr/include/freetype2 -Iinclude -c /home/liliane/Documentos/GIT/gcgtube/source/Visualizer/nanotube.cpp -o obj/Release/Visualizer/nanotube.o
g++ -std=c++11 -march=core2 -fexpensive-optimizations -O3 -Wall -std=c++11 -I../Library/include -I../../external/include -I/home/liliane/Documentos/Libs/glfw-3.2/build/src -I/usr/include/freetype2 -Iinclude -c /home/liliane/Documentos/GIT/gcgtube/source/Visualizer/NanotubeMaterial.cpp -o obj/Release/Visualizer/NanotubeMaterial.o
g++ -std=c++11 -march=core2 -fexpensive-optimizations -O3 -Wall -std=c++11 -I../Library/include -I../../external/include -I/home/liliane/Documentos/Libs/glfw-3.2/build/src -I/usr/include/freetype2 -Iinclude -c /home/liliane/Documentos/GIT/gcgtube/source/Visualizer/OrbitCamera.cpp -o obj/Release/Visualizer/OrbitCamera.o
g++ -std=c++11 -march=core2 -fexpensive-optimizations -O3 -Wall -std=c++11 -I../Library/include -I../../external/include -I/home/liliane/Documentos/Libs/glfw-3.2/build/src -I/usr/include/freetype2 -Iinclude -c /home/liliane/Documentos/GIT/gcgtube/source/Visualizer/Source.cpp -o obj/Release/Visualizer/Source.o
g++ -std=c++11 -march=core2 -fexpensive-optimizations -O3 -Wall -std=c++11 -I../Library/include -I../../external/include -I/home/liliane/Documentos/Libs/glfw-3.2/build/src -I/usr/include/freetype2 -Iinclude -c /home/liliane/Documentos/GIT/gcgtube/source/Visualizer/SuperBlock.cpp -o obj/Release/Visualizer/SuperBlock.o
g++ -std=c++11 -march=core2 -fexpensive-optimizations -O3 -Wall -std=c++11 -I../Library/include -I../../external/include -I/home/liliane/Documentos/Libs/glfw-3.2/build/src -I/usr/include/freetype2 -Iinclude -c /home/liliane/Documentos/GIT/gcgtube/source/Visualizer/Visualizer.cpp -o obj/Release/Visualizer/Visualizer.o
g++ -std=c++11 -march=core2 -fexpensive-optimizations -O3 -Wall -std=c++11 -I../Library/include -I../../external/include -I/home/liliane/Documentos/Libs/glfw-3.2/build/src -I/usr/include/freetype2 -Iinclude -c /home/liliane/Documentos/GIT/gcgtube/source/Visualizer/VisualizerCommon.cpp -o obj/Release/Visualizer/VisualizerCommon.o
g++ -L../../lib -o ../../build/Release/Visualizer obj/Release/Library/Text2D.o obj/Release/Visualizer/Block.o obj/Release/Visualizer/CatmullRom.o obj/Release/Visualizer/Contact.o obj/Release/Visualizer/DrawableNanotube.o obj/Release/Visualizer/DrawableSpheres.o obj/Release/Visualizer/Forest.o obj/Release/Visualizer/Graph.o obj/Release/Visualizer/Laplacian.o obj/Release/Visualizer/LinearSolver.o obj/Release/Visualizer/nanotube.o obj/Release/Visualizer/NanotubeMaterial.o obj/Release/Visualizer/OrbitCamera.o obj/Release/Visualizer/Source.o obj/Release/Visualizer/SuperBlock.o obj/Release/Visualizer/Visualizer.o obj/Release/Visualizer/VisualizerCommon.o  -s  -lGLEW /home/liliane/Documentos/Libs/glfw-3.2/build/src/libglfw.so -lGL -lX11 -lpthread -lXrandr -lXi -lXcursor -lgsl -lgslcblas /usr/lib/x86_64-linux-gnu/libfreetype.so /usr/lib/x86_64-linux-gnu/libpng12.a /usr/lib/x86_64-linux-gnu/libz.a /home/liliane/Documentos/GIT/gcgtube/lib/libLibraryd.so
